### ISSUE TITLE
Commands failing

### ISSUE THREAD

**Issue by AstraLuma** [WeAllJS/wheelie-slack-app#29]
![image](https://user-images.githubusercontent.com/401438/226747374-a77d9614-ab88-4aca-83ab-2626ba1f1734.png)

![image](https://user-images.githubusercontent.com/401438/226747401-c9071050-8b8e-4d71-8780-ac2f7ae1f56a.png)

**Comment by AstraLuma** [comment]
@asymmetricia said they'd take a stab at this

**Comment by asymmetricia** [comment]
Hi, @zkat. Any chance we can get the full logs from start to finish for the app?

**Comment by AstraLuma** [comment]
My suggestion is to toss in a bunch more logging to figure out what exactly is going on.

**Comment by zkat** [comment]
@asymmetricia 

```
2023-03-21T21:43:59.196412+00:00 heroku[web.1]: State changed from starting to crashed
2023-03-21T21:43:59.199434+00:00 heroku[web.1]: State changed from crashed to starting
2023-03-21T21:44:00.822733+00:00 heroku[web.1]: Starting process with command `npm start`
2023-03-21T21:44:02.167265+00:00 app[web.1]: 
2023-03-21T21:44:02.167306+00:00 app[web.1]: > wheelie-slack-app@1.0.0 start /app
2023-03-21T21:44:02.167306+00:00 app[web.1]: > node server.js
2023-03-21T21:44:02.167306+00:00 app[web.1]: 
2023-03-21T21:44:02.703784+00:00 app[web.1]: launching bot for XXX1
2023-03-21T21:44:02.715670+00:00 app[web.1]: launching bot for XXX2
2023-03-21T21:44:02.717847+00:00 app[web.1]: launching bot for XXX3
2023-03-21T21:44:02.719205+00:00 app[web.1]: launching bot for XXX4
2023-03-21T21:44:02.720450+00:00 app[web.1]: launching bot for XXX5
2023-03-21T21:44:02.721787+00:00 app[web.1]: launching bot for XXX6
2023-03-21T21:44:02.723273+00:00 app[web.1]: launching bot for XXX7
2023-03-21T21:44:02.724320+00:00 app[web.1]: launching bot for XXX8
2023-03-21T21:44:02.725650+00:00 app[web.1]: launching bot for XXX9
2023-03-21T21:44:02.726915+00:00 app[web.1]: launching bot for XXX10
2023-03-21T21:44:02.764867+00:00 app[web.1]: failure launching bot for  XXX3 account_inactive
2023-03-21T21:44:02.812750+00:00 app[web.1]: events.js:154
2023-03-21T21:44:02.812756+00:00 app[web.1]:       throw er; // Unhandled 'error' event
2023-03-21T21:44:02.812756+00:00 app[web.1]:       ^
2023-03-21T21:44:02.812756+00:00 app[web.1]: 
2023-03-21T21:44:02.812757+00:00 app[web.1]: Error: certificate has expired
2023-03-21T21:44:02.812757+00:00 app[web.1]:     at Error (native)
2023-03-21T21:44:02.812758+00:00 app[web.1]:     at TLSSocket.<anonymous> (_tls_wrap.js:1065:38)
2023-03-21T21:44:02.812759+00:00 app[web.1]:     at emitNone (events.js:80:13)
2023-03-21T21:44:02.812759+00:00 app[web.1]:     at TLSSocket.emit (events.js:179:7)
2023-03-21T21:44:02.812761+00:00 app[web.1]:     at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:593:8)
2023-03-21T21:44:02.812761+00:00 app[web.1]:     at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:425:38)
2023-03-21T21:44:02.819709+00:00 app[web.1]: 
2023-03-21T21:44:02.824476+00:00 app[web.1]: npm ERR! Linux 4.4.0-1104-aws
2023-03-21T21:44:02.824696+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2023-03-21T21:44:02.824773+00:00 app[web.1]: npm ERR! node v5.9.1
2023-03-21T21:44:02.824975+00:00 app[web.1]: npm ERR! npm  v3.7.3
2023-03-21T21:44:02.825043+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2023-03-21T21:44:02.825098+00:00 app[web.1]: npm ERR! wheelie-slack-app@1.0.0 start: `node server.js`
2023-03-21T21:44:02.825212+00:00 app[web.1]: npm ERR! Exit status 1
2023-03-21T21:44:02.825338+00:00 app[web.1]: npm ERR! 
2023-03-21T21:44:02.825339+00:00 app[web.1]: npm ERR! Failed at the wheelie-slack-app@1.0.0 start script 'node server.js'.
2023-03-21T21:44:02.825341+00:00 app[web.1]: npm ERR! Make sure you have the latest version of node.js and npm installed.
2023-03-21T21:44:02.825407+00:00 app[web.1]: npm ERR! If you do, this is most likely a problem with the wheelie-slack-app package,
2023-03-21T21:44:02.825474+00:00 app[web.1]: npm ERR! not with npm itself.
2023-03-21T21:44:02.825540+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2023-03-21T21:44:02.825604+00:00 app[web.1]: npm ERR!     node server.js
2023-03-21T21:44:02.825669+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2023-03-21T21:44:02.825745+00:00 app[web.1]: npm ERR!     npm bugs wheelie-slack-app
2023-03-21T21:44:02.825810+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2023-03-21T21:44:02.825864+00:00 app[web.1]: npm ERR!     npm owner ls wheelie-slack-app
2023-03-21T21:44:02.825913+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2023-03-21T21:44:02.828030+00:00 app[web.1]: 
2023-03-21T21:44:02.828149+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2023-03-21T21:44:02.828196+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2023-03-21T21:44:02.968723+00:00 heroku[web.1]: Process exited with status 1
2023-03-21T21:44:03.014420+00:00 heroku[web.1]: State changed from starting to crashed
```

That npm-debug.log almost certainly does not contain more detail than is already displayed, although I don't know how to access that file from heroku.

**Comment by asymmetricia** [comment]
thx! one hypothesis I have is that the redis instance that's configured is the thing with an expired cert; can you share the hostname, and/or check it's cert with qualys or `openssl s_client`?

**Comment by zkat** [comment]
@asymmetricia would it be helpful if I gave you temp access to the heroku app?

**Comment by asymmetricia** [comment]
sure!

**Comment by zkat** [comment]
@asymmetricia give me a heroku email (or DM it to me somewhere? You can also email my public github email on my profile), and I'll add you :)

**Comment by asymmetricia** [comment]
emailed!

**Comment by asymmetricia** [comment]
OK, so the issue is that this is node 5, and the SSL CA certificate store in whatever heroku is providing for node 5 is woefully out of date; so the _root_ certificate it has for the end of the chain for https://slack.com _is_ in fact expired. The certificate expired issue comes as soon as one of the several async code paths attempts to actually connect to the Slack API.

I'm fiddling around to see what the best option will be, but it's one of:
1) update node
2) somehow update the certificate store in the heroku dyno
3) convince the slack client to ignore certificate validation

**Comment by zkat** [comment]
probably not a terrible idea to update node anyway, tbh

**Comment by asymmetricia** [comment]
@zkat The PR updates it to node 19, which is working in my extremely simplistic local tests. We're totally offline now, so it can't be much worse to try it live.

**Comment by zkat** [comment]
@asymmetricia This is what I got when deploying this:
```
-----> Building on the Heroku-20 stack
-----> Using buildpack: heroku/nodejs
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       
-----> Installing binaries
       engines.node (package.json):  19.8.1
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 19.8.1...
       Could not find Node version corresponding to version requirement: 19.8.1
-----> Build failed
 !     No matching version found for Node: 19.8.1
       Heroku supports the latest Stable version of Node.js as well as all
       active LTS (Long-Term-Support) versions, however you have specified
       a version in package.json (19.8.1) that does not correspond to
       any published version of Node.js.
       You should always specify a Node.js version that matches the runtime
       you’re developing and testing with. To find your version locally:
       $ node --version
       v6.11.1
       Use the engines section of your package.json to specify the version of
       Node.js to use on Heroku. Drop the ‘v’ to save only the version number:
       "engines": {
         "node": "6.11.1"
       }
    
       https://help.heroku.com/6235QYN4/
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

**Comment by asymmetricia** [comment]
oops, yep. https://github.com/WeAllJS/wheelie-slack-app/pull/33 should solve that.

**Comment by zkat** [comment]
deployment went ok, but the vendoring went sideways. Why did you end up vendoring that package?

```
2023-03-21T23:59:39.183438+00:00 app[web.1]: Unexpected handler execution error: Error: Cannot find module '/app/node_modules/@inklesspen/genderrolls/dist/index.js'. Please verify that the package.json has a valid "main" entry
```

**Comment by asymmetricia** [comment]
ugh, weird. I vendored it because the original package isn't in the npm
registry anymore, and having npm fetching it from github was not working
correctly inside docker.

Let me see if I can sort this out and/or come up with a third option..

**Comment by zkat** [comment]
@asymmetricia honestly, feel free to yank out the genderroll command altogether, imo. I'm surprised it's not on NPM anymore, too, but I guess it may have gotten yanked before NPM started disallowing full unpublish.

**Comment by asymmetricia** [comment]
Let's try https://github.com/WeAllJS/wheelie-slack-app/pull/34 and if that doesn't work we can pull it all out.

**Comment by zkat** [comment]
Fix deployed and I've confirmed that /list-private works on WeAllJS. I'm gonna assume it works on lgbtq.tech, too :)

**Comment by zkat** [comment]
Thanks a ton for the help taking care of this, @asymmetricia!

**Comment by asymmetricia** [comment]
Defo! Thanks for working through it with me.
